[package]
name = "testcrate"
version = "0.1.0"
authors = ["Aleksandr Orlenko <zxteam@protonmail.com>"]
edition = "2021"
publish = false

[features]
lua52compat = []

[build-dependencies]
luajit-src = { path = ".." }
